-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:Samsung Electric Company LS24D60xU HNAXC00823",
  mode = "2560x1440@59.95",
  position = "2048x0",
  scale = 1.07,
  bitdepth = 10,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})

hl.monitor({
  output = "desc:AU Optronics 0xC199",
  disabled = true,
})
