-- Generated by hyprmoncfg

hl.monitor({
  output = "desc:AU Optronics 0xC199",
  mode = "2560x1600@60.03",
  position = "0x0",
  scale = 1.25,
  sdr_min_luminance = 0.2,
  sdr_max_luminance = 80,
})
